#!/usr/bin/perl

=head1 NAME

easy_pages_paths 

=head1 DESCRIPTION

Provide list of existing paths to aid with multiple language support

=cut

use EPrints;

use strict;

my $session = EPrints::Session->new();

my $q = $session->param( "q" ) || "";

my $database = $session->get_database;
my $dataset = $session->dataset( "page" );
# my @ids = $dataset->search->ids;
# my $pages = $dataset->list( \@ids );

# my $searchexp = new EPrints::Search( session=>$session, dataset=>$dataset );
# my $results = $searchexp->perform_search;

my @rows;
my @paths;

$dataset->search->map( sub {
    my( undef, undef, $page ) = @_;
    my $path = $page->get_value("path");

    if ($path ne ""){

        push @paths, $path;
    }

});

# foreach my $page ($pages)
# {
#     push @paths, $page->get_value("path");
# }

foreach my $path ( @paths ){
  
	
    my $row = {};
	push @rows, $row;

	my $frag = $session->make_doc_fragment;

	$frag->appendChild( $session->make_text( $path ) );

	$row->{xhtml} = $frag;
	$row->{values} = [
		"for:value:component:_path" => $path,
	];
}

my $ul = EPrints::Extras::render_lookup_list( $session, \@rows );

$session->send_http_header( content_type => "text/xml; charset=UTF-8" );

binmode(STDOUT,":utf8");
print <<END;
<?xml version="1.0" encoding="UTF-8" ?>

END
print EPrints::XML::to_string( $ul, "utf-8", 1 );

EPrints::XML::dispose( $ul );

$session->terminate;

